---
title: "Sokolova, Biehl TSA Competition"
author: "Tatiana Sokolova, Kevin Biehl"
date: "4/13/2022"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE)
```

```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(readxl)
```


```{r data}
#Importing data
load <- read_excel("./Data/load.xlsx")

#Aggregating from hourly to daily and omitting NAs from the calculation
DailyAvgLoad <- rowMeans(load[,3:26], na.rm=TRUE) 

DailyAvgLoad <- data.frame(load$date,DailyAvgLoad)
colnames(DailyAvgLoad) <- c("Date","Load")
DailyAvgLoad$Date <- ymd(DailyAvgLoad$Date)

ggplot(DailyAvgLoad, aes(x=Date,y=Load)) +
  geom_line() +
  ggtitle("Average Daily Load")+
  ylab("Load")

summary(DailyAvgLoad$Load)

```


```{r ts, message=FALSE, warning=FALSE}
#Making time series
ts_DailyAvgLoad <- msts(DailyAvgLoad$Load, 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,1,1))

#Decomposing the series                           
ts_DailyAvgLoad %>% mstl() %>%
  autoplot()

```

```{r train, message=FALSE, warning=FALSE}
#subset for training
n_forecast = 365
ts_DailyAvgLoad_train <- subset(ts_DailyAvgLoad,
                                   end = length(ts_DailyAvgLoad)-n_forecast)

#subset for testing
ts_DailyAvgLoad_test <- subset(ts_DailyAvgLoad,
                                   start = length(ts_DailyAvgLoad)-n_forecast)

autoplot(ts_DailyAvgLoad_train)
autoplot(ts_DailyAvgLoad_test)
```

#Forecasting using STL+ETS (Model 1)

```{r ETS, echo=TRUE, message=FALSE, warning=FALSE}
#Fit and forecast STL + ETS model to data
ETS_fit <- stlf(ts_DailyAvgLoad_train,h=365)

#Plot foresting results
autoplot(ETS_fit) + ylab("Average Load") #ANN = additive, no trend, non-seasonal

#Plot model + observed data
autoplot(ts_DailyAvgLoad) +
  autolayer(ETS_fit, series="STL + ETS",PI=FALSE) +
  ylab("Average Load")

```

#Forecasting using ARIMA + Fourier (Model 2)
```{r ARIMA, echo=TRUE, message=FALSE, warning=FALSE}

ARIMA_Four_fit <- auto.arima(ts_DailyAvgLoad_train, 
                             seasonal=FALSE, #P,D,Q = 0
                             lambda=0,
                             xreg=fourier(ts_DailyAvgLoad_train, 
                                          K=c(2,12))
                             )

#Forecast with ARIMA fit
ARIMA_Four_for <- forecast::forecast(ARIMA_Four_fit,
                           xreg=fourier(ts_DailyAvgLoad_train,
                                        K=c(2,12),
                                        h=365), #generates fourier terms 365 step ahead of time
                           h=365 
                           ) 

#Plot foresting results
autoplot(ARIMA_Four_for) + ylab("Average Load")

#Plot model + observed data
autoplot(ts_DailyAvgLoad) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER",PI=FALSE) +
  ylab("Average Load")

```

#Forecasting using TBATS (Model 3)
```{r TBATS, echo=TRUE, message=FALSE, warning=FALSE}
TBATS_fit <- tbats(ts_DailyAvgLoad_train)

TBATS_for <- forecast::forecast(TBATS_fit, h=365)

#Plot foresting results
autoplot(TBATS_for) +
  ylab("Average Load") 

#Plot model + observed data
autoplot(ts_DailyAvgLoad) +
  autolayer(TBATS_for, series="TBATS",PI=FALSE)+
  ylab("Average Load") 

```

#Forecasting using Neural Network Time Series (Model 4)

```{r NNETAR, echo=TRUE, message=FALSE, warning=FALSE}

NN_fit <- nnetar(ts_DailyAvgLoad_train,p=1,P=0,xreg=fourier(ts_DailyAvgLoad_train, K=c(2,12)))

NN_for <- forecast::forecast(NN_fit, h=365,xreg=fourier(ts_DailyAvgLoad_train, 
                                          K=c(2,12),h=365))

#Plot foresting results
autoplot(NN_for) +
  ylab("Average Load") 

#Plot model + observed data
autoplot(ts_DailyAvgLoad) +
  autolayer(NN_for, series="Neural Network",PI=FALSE)+
  ylab("Average Load") 

```

# Checking accuracy of the models

```{r accuracy}

#Model 1: STL + ETS
ETS_scores <- accuracy(ETS_fit$mean,ts_DailyAvgLoad_test)  

#Model 2: ARIMA + Fourier 
ARIMA_scores <- accuracy(ARIMA_Four_for$mean,ts_DailyAvgLoad_test)

# Model 3:  TBATS 
TBATS_scores <- accuracy(TBATS_for$mean,ts_DailyAvgLoad_test)

# Model 4:  Neural Network 
NN_scores <- accuracy(NN_for$mean,ts_DailyAvgLoad_test)

```

# Comparing Performance metrics
```{r comparing}
#creating data frame
scores <- as.data.frame(
  rbind(ETS_scores, ARIMA_scores, TBATS_scores, NN_scores)
  )
row.names(scores) <- c("STL+ETS", "ARIMA+Fourier","TBATS","NN")

#choosing model with lowest RMSE
best_model_index <- which.min(scores[,"RMSE"])
cat("The best model by RMSE is:", row.names(scores[best_model_index,]))                       
```

```{r table, echo=FALSE, message=FALSE, warning=FALSE}
#generating table to compare
kbl(scores, 
      caption = "Forecast Accuracy for Daily Average Load",
      digits = array(5,ncol(scores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"RMSE"]))
```


```{r together}
autoplot(ts_DailyAvgLoad) +
  autolayer(ETS_fit, PI=FALSE, series="STL+ETS") +
  autolayer(ARIMA_Four_for, PI=FALSE, series="ARIMA + Fourier") +
  autolayer(TBATS_for,PI=FALSE, series="TBATS") +
  autolayer(NN_for,PI=FALSE, series="NN") +
  xlab("Day") + ylab("Daily Average Load") +
  guides(colour=guide_legend(title="Forecast"))
```

#Forecasting Daily Demand for January 2011

Since TBATS was determined to be the best model:
```{r TBATS, echo=TRUE, message=FALSE, warning=FALSE}
TBATS11_fit <- tbats(ts_DailyAvgLoad)

TBATS11_for <- forecast::forecast(TBATS11_fit, h=31)

#Plot foresting results
autoplot(TBATS11_for) +
  ylab("Average Load") 

#Plot model + observed data
autoplot(ts_DailyAvgLoad) +
  autolayer(TBATS11_for, series="TBATS",PI=FALSE)+
  ylab("Average Load") 

write.csv(TBATS11_for, file="./Outputs/TBATS_forecast.csv")
```